## Special Task 13

# Movie Recommender System for Groups of People

Most movie streaming websites nowadays use recommender systems in order to cater to their user's needs. But what do you do when you want to watch a movie with your group of friends? It seems like an impossible task since such websites only take into account one user's personal preferences when trying to predict how much they'll like a certain movie. But I believe there is a solution to make streaming services more accomodating to group viewings.
<br>
<br>
The algorithm K Nearest Neighbors is commonly used in order to predict a person's preferences based on previous activity, by using data provided by other users. A User-User collaborative filtering model based on K-NN could be improved to include preferences from multiple people when making a prediction for that whole group. 
<br>
<br>
Presuming each user has a dataset of ratings (from 1.0 to 5.0) for the movies they have watched, a good starting point would be to create a new dataset containing as ratings the averages of the ratings given by the group members. This could be obtained automatically if the respective streaming website offered to users a feature such as "watch with friends", which would allow a user to select the friends they are watching with (as long as they also have accounts on that website) in order to merge their datasets. Since it's very likely that there are movies that only a part of the group has watched, the average should be computed as follows:
<br>
average_rating = sum_of_ratings_from_group_members/number_of_group_members_that_have_watched_the_movie.
<br>
<br>
Some additional changes could be made to improve the algorithm further. For example, movies for which any individual group member would normally have a very low predicted appreciation could be automatically eliminated from the list of suggestions for the group.
<br>
<br>
Taking into consideration the popularity of online streaming services and the enjoyment that people get from watching movies and series together, I think this idea is a very potentially useful one.
<br>
<br>
References:
1. F. Maxwell Harper and Joseph A. Konstan. 2015. The MovieLens Datasets: History and Context. ACM Transactions on Interactive Intelligent Systems (TiiS) 5, 4: 19:1–19:19. https://doi.org/10.1145/2827872 <br>
2. Nilashi, Mehrbakhsh & Bagherifard, Karamollah & Ibrahim, Assoc Prof. Dr. Othman & Alizadeh, Hamid & Lasisi, Ayodele & Roozegar, Nazanin. (2013). Collaborative Filtering Recommender Systems. Research Journal of Applied Sciences, Engineering and Technology. 5. 4168-4182. 10.19026/rjaset.5.4644. https://www.researchgate.net/publication/287952023

In [26]:
#The purpose of this lab is to create a maze solver.

In [27]:
from PIL import Image, ImageDraw

In [28]:
#We have the following data
#A is the maze matrix where 0 are the path wich are avaible and 1 are the walls
#Start is the start point of the player
#End is the maze exit

In [29]:
images = []

a = [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0 ,0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0 ,0, 0, 1, 1, 1, 1, 0, 0, 1],
    [1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0 ,0, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1 ,0, 1, 1, 1, 0, 1, 1, 1, 1],
    [1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0 ,0, 1, 0, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0 ,0, 1, 0, 1, 1, 1, 1, 1, 1],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0 ,0, 0, 0, 0, 1, 0, 0, 0, 1],
    [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0 ,0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
]
zoom = 20
borders = 6
start = 1,1
end = 5,19

In [ ]:
#The print_m method will be used to print the matrix
#The draw_matrix is used to generate the gif, generation a new image for every move

In [30]:
def draw_matrix(a,m, the_path = []):
    im = Image.new('RGB', (zoom * len(a[0]), zoom * len(a)), (255, 255, 255))
    draw = ImageDraw.Draw(im)
    for i in range(len(a)):
        for j in range(len(a[i])):
            color = (255, 255, 255)
            r = 0
            if a[i][j] == 1:
                color = (0, 0, 0)
            if i == start[0] and j == start[1]:
                color = (0, 255, 0)
                r = borders
            if i == end[0] and j == end[1]:
                color = (0, 255, 0)
                r = borders
            draw.rectangle((j*zoom+r, i*zoom+r, j*zoom+zoom-r-1, i*zoom+zoom-r-1), fill=color)
            if m[i][j] > 0:
                r = borders
                draw.ellipse((j * zoom + r, i * zoom + r, j * zoom + zoom - r - 1, i * zoom + zoom - r - 1),fill=(255,0,0))
    for u in range(len(the_path)-1):
        y = the_path[u][0]*zoom + int(zoom/2)
        x = the_path[u][1]*zoom + int(zoom/2)
        y1 = the_path[u+1][0]*zoom + int(zoom/2)
        x1 = the_path[u+1][1]*zoom + int(zoom/2)
        draw.line((x,y,x1,y1), fill=(255, 0,0), width=5)
    draw.rectangle((0, 0, zoom * len(a[0]), zoom * len(a)), outline=(0,255,0), width=2)
    images.append(im)

In [31]:
import numpy as np

#Task 0
#Fill the matrix with zeros and 1 on the start position
#TODO
m = []
for i in range(len(a)):
    m.append([])
    for j in range(len(a[i])):
        m[-1].append(0)
i,j = start
m[i][j] = 1
print(np.matrix(m))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [23]:
#Now we have to implement the make_step function which is the core of the algorithm
#The function get one parameter k which represent the current step
#On every step we need to find the next valid move and mark that move with k + 1

In [32]:
def make_step(k):
    for i in range(len(m)):
        for j in range(len(m[i])):
              if m[i][j] == k:
                    if i>0 and m[i-1][j] == 0 and a[i-1][j] == 0:
                          m[i-1][j] = k + 1
                    if j>0 and m[i][j-1] == 0 and a[i][j-1] == 0:
                          m[i][j-1] = k + 1
                    if i<len(m)-1 and m[i+1][j] == 0 and a[i+1][j] == 0:
                          m[i+1][j] = k + 1
                    if j<len(m[i])-1 and m[i][j+1] == 0 and a[i][j+1] == 0:
                          m[i][j+1] = k + 1

In [33]:
k = 0
while m[end[0]][end[1]] == 0:
    k += 1
    make_step(k)
    draw_matrix(a, m)


i, j = end
k = m[i][j]
the_path = [(i,j)]
while k > 1:
    if i > 0 and m[i - 1][j] == k-1:
        i, j = i-1, j
        the_path.append((i, j))
        k-=1
    elif j > 0 and m[i][j - 1] == k-1:
        i, j = i, j-1
        the_path.append((i, j))
        k-=1
    elif i < len(m) - 1 and m[i + 1][j] == k-1:
        i, j = i+1, j
        the_path.append((i, j))
        k-=1
    elif j < len(m[i]) - 1 and m[i][j + 1] == k-1:
        i, j = i, j+1
        the_path.append((i, j))
        k -= 1
    draw_matrix(a, m, the_path)

for i in range(10):
    if i % 2 == 0:
        draw_matrix(a, m, the_path)
    else:
        draw_matrix(a, m)

print_m(m)
print(the_path)

0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  
0  1  0  25 24 23 22 21 20 0  22 23 24 25 26 27 28 29 30 0  
0  2  0  26 0  22 21 20 19 20 21 22 23 0  0  0  0  30 31 0  
0  3  0  27 0  0  0  0  18 0  22 23 24 25 26 27 28 29 30 0  
0  4  0  28 0  0  0  0  17 0  0  24 0  0  0  28 0  0  0  0  
0  5  0  0  0  0  0  0  16 0  26 25 0  31 0  29 30 31 32 33 
0  6  7  8  9  10 11 0  15 0  27 26 0  30 0  0  0  0  0  0  
0  0  0  9  10 11 12 13 14 0  28 27 28 29 30 0  0  0  0  0  
0  0  0  10 11 12 13 14 15 0  29 28 29 0  31 32 33 0  0  0  
0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  
[(5, 19), (5, 18), (5, 17), (5, 16), (5, 15), (4, 15), (3, 15), (3, 14), (3, 13), (3, 12), (2, 12), (2, 11), (2, 10), (2, 9), (2, 8), (3, 8), (4, 8), (5, 8), (6, 8), (7, 8), (7, 7), (7, 6), (6, 6), (6, 5), (6, 4), (6, 3), (6, 2), (6, 1), (5, 1), (4, 1), (3, 1), (2, 1), (1, 1)]


In [ ]:
Expected result
The matrix:
0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  
0  1  0  25 24 23 22 21 20 0  22 23 24 25 26 27 28 29 30 0  
0  2  0  26 0  22 21 20 19 20 21 22 23 0  0  0  0  30 31 0  
0  3  0  27 0  0  0  0  18 0  22 23 24 25 26 27 28 29 30 0  
0  4  0  28 0  0  0  0  17 0  0  24 0  0  0  28 0  0  0  0  
0  5  0  0  0  0  0  0  16 0  26 25 0  31 0  29 30 31 32 33 
0  6  7  8  9  10 11 0  15 0  27 26 0  30 0  0  0  0  0  0  
0  0  0  9  10 11 12 13 14 0  28 27 28 29 30 0  0  0  0  0  
0  0  0  10 11 12 13 14 15 0  29 28 29 0  31 32 33 0  0  0  
0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  

The path
[(5, 19), (5, 18), (5, 17), (5, 16), (5, 15), (4, 15), (3, 15), (3, 14), (3, 13), (3, 12), (2, 12), (2, 11), (2, 10), (2, 9), (2, 8), (3, 8), (4, 8), (5, 8), (6, 8), (7, 8), (7, 7), (7, 6), (6, 6), (6, 5), (6, 4), (6, 3), (6, 2), (6, 1), (5, 1), (4, 1), (3, 1), (2, 1), (1, 1)]

In [ ]:
#For a visual representation of the algorithm we have the following code

In [34]:
images[0].save('maze.gif',
               save_all=True, append_images=images[1:],
               optimize=False, duration=1, loop=0)

In [7]:
#Expected result in the expectedMaze.gif file

'[alt' is not recognized as an internal or external command,
operable program or batch file.
